# Generated by Django 3.0.2 on 2020-08-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_category_parent_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
